AllCops:
  TargetRubyVersion: 2.3.8

#
# Default Preferences
#

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/CommentedKeyword:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

#
# Adjustable Parameters
#

Metrics/AbcSize:
  Exclude:
    - 'spec/locator_spec_helper.rb'

Metrics/MethodLength:
  Max: 11